### ISSUE TITLE
How do I know if some of the dependencies are impossible to resolve?

### ISSUE THREAD

**Issue by loki2302** [viaplay/simple-ioc#9]
As a simple-ioc user who writes a bunch of system/integration tests, I want the container to tell me if something is wrong with the configuration aloud. Here's a piece of code I have:
```javascript
var ioc = require('simple-ioc');

describe('simple-ioc', function() {
  it('should fail when there is no dependency', function(done) {
    ioc
      .getContainer()
      .inject(function(a) { // right, there's no "a"
        done();
      });
  });
});
```
When this test gets started, Mocha just silently shuts down. Neither my "inject" callback is called, nor any tests after this one get executed. I'm on Node v0.11.14, simple-ioc version is 3.0.13.

**Comment by CKing** [comment]
Here is your test modified to this use case:

```javascript
var ioc = require('simple-ioc');

describe('simple-ioc', function() {
  it('should fail when there is no dependency', function(done) {
    ioc
      .getContainer()
      .resolve("a", function(err, inst) {
        if (!!err) { return done(err); } // something failed miserably
        done();
      });
  });
});
```

this only works with a single module though.

**Comment by loki2302** [comment]
That's what I needed, thanks!
